# Imagen base de OpenJDK con Alpine Linux
FROM openjdk:17-jdk-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copiar el archivo JAR de la aplicación
COPY ./target/presentacion-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto de la API 
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "app.jar"]
